version: '3.3'

services:
   redis:
     image: redis:latest
     restart: always
     network_mode: "bridge"
   db:
     image: mysql:latest
     command: --default-authentication-plugin=mysql_native_password
     volumes:
       - db_data:/var/lib/mysql
       - ./sql:/sql
     restart: always
     network_mode: "bridge"
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wechat
       MYSQL_USER: wechat
       MYSQL_PASSWORD: wechat
   laravel:
     depends_on:
        - db
        - redis
     links:
        - db:mysql
        - redis
     # image: guoxiangke/wechat:laravel56
     build: ./laravel
     network_mode: "bridge"
     restart: always
     volumes:
        - ./laravel/storage/app:/var/www/html/storage/app
        - /tmp:/tmp
        - ./laravel/cert:/var/www/html/cert:ro
        - ./laravel/.env.production:/var/www/html/.env
        - ./config/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
        #patches for aws: https://github.com/overtrue/wechat/issues/1356
        - ./patches/CurlMultiHandler.php:/var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:ro
        #https://github.com/rinvex/laravel-subscriptions/issues/42
        - ./patches/Period.php:/var/www/html/vendor/rinvex/subscriptions/src/Services/Period.php:ro
     environment:
        REDIS_PORT: 6379
        APP_ENV: production
        VIRTUAL_HOST: wechat.yongbuzhixi.com #wechat.gg.daxiangyingyu.com
        LETSENCRYPT_HOST: wechat.yongbuzhixi.com
        LETSENCRYPT_EMAIL: dale.tel@139.com


volumes:
    db_data:
